name: Create PR from Sub-Branch to Main

on:
  push:
    branches:
      - 'feature/*'  # feature/* 형태의 서브 브랜치에서 push가 발생할 때

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"

      - name: Create Pull Request to Main
        run: |
          pr_title="Auto PR from $GITHUB_REF"
          pr_body="This PR is created automatically from branch $GITHUB_REF"
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title":"'"$pr_title"'","body":"'"$pr_body"'","head":"'"$GITHUB_REF"'","base":"main"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls
